### ISSUE TITLE
[checkm8_t8010] ERROR: Failed to generate payload!

### ISSUE THREAD

**Issue by potryasas** [dora2-iOS/ipwnder_lite#7]
How to fix it?

**Comment by dora2-iOS** [comment]
Please report in more detail. (device, environment, error details, etc.)

**Comment by potryasas** [comment]
Iphone 7, ios 15.4.1 
Full log:
`macbook@MacBook-Air-macbook ipwnder_lite % sudo ./ipwnder_macosx -p
[main] Waiting for device in DFU mode...
[main] CONNECTED
[main] CPID: 0x8010, BDID: 0x0c, STRG: [iBoot-2696.0.0.1.33]
[checkm8_t8010] ERROR: Failed to generate payload!
macbook@MacBook-Air-macbook ipwnder_lite %`
